/** Figma 节点 4005:86272 中导出的全部图标名称。 */
export const figmaIconNames = [
  "home",
  "folder",
  "workflow",
  "workflow-fill",
  "folder-fill",
  "wechat-fill",
  "list-fill",
  "profile-fill",
  "wechat",
  "bell",
  "list",
  "email",
  "home-fill",
  "profile",
  "more",
  "add",
  "history",
  "render",
  "component-2",
  "pen",
  "close",
  "arrow-down",
  "star",
  "like-fill",
  "arrow-right",
  "check",
  "check-fill",
  "check-2",
  "add-2",
  "search",
  "export",
  "experimental",
  "share",
  "upload-image",
  "magic",
  "aspect-ratio-9-16",
  "import",
  "dev",
  "playing",
  "clock-stopwatch",
  "play",
  "minus",
  "right",
  "like",
  "audio-media",
  "text",
  "photo",
  "video",
  "warning-fill",
  "deals",
  "star-fill",
  "alipay",
  "wechat-pay",
  "task",
  "task-fill",
  "arrow-right-2",
  "advanced-features",
  "loading",
  "audio",
  "more-compact",
  "buildings",
  "eye",
] as const;

export type FigmaIconName = (typeof figmaIconNames)[number];

const iconModules = import.meta.glob<string>("./*.svg", {
  eager: true,
  import: "default",
  query: "?url",
});

/** 图标名到本地 SVG URL 的类型安全映射。 */
export const figmaIcons = Object.fromEntries(
  figmaIconNames.map((name) => [name, iconModules[`./${name}.svg`]]),
) as Record<FigmaIconName, string>;
